In [1]:
import numpy as np

# Arrays

Initialization Of Arrays

In [2]:
ar1=np.array([1,2,3,4,5,6,7]) # array initializing by passing a list directly
ar1   

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
l=[10,9,8,7,6]
ar2=np.array(l)    # another way of Initializing array by passing a list
ar2

array([10,  9,  8,  7,  6])

In [4]:
ar2.dtype    # Will tell the data type of your array.

dtype('int32')

In [5]:
ar1.ndim    # Will return the dimension of your array... example- 1D/2D/3D and so on...

1

In [6]:
ar2.size    # Will return the number of elements in your array

5

# More numpy functions


In [7]:
arr=np.linspace(0,10,11)    # Syntax - linspace(start,stop,count)
arr                         # It returns a numpy array with equally linearly spaced 10 elements of 0 to 10. 
                            # Default value of "count" arguement is 50.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
arr1=np.arange(1,15,2)  # Syntax - arange(start,stop,skip)
arr1                    # It returns a numpy array from 1 to 15, skipping 2 elements in between.  

array([ 1,  3,  5,  7,  9, 11, 13])

In [9]:
arr2=np.logspace(1,40,5)  # Syntax - logspace(start,stop,number_of_values)
arr2                      #Return 5 numbers spaced evenly on a log scale from 1-40

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [10]:
arr3=np.zeros(2)    # Returns a numpy array of zeros with 2 elements. 
arr3                    

array([0., 0.])

In [11]:
arr4=np.ones(5,int)     # Returns a numpy array of zeros with 2 integer elements.
arr4

array([1, 1, 1, 1, 1])

In [12]:
arr5=np.identity(3,int)
arr5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
arr1.nbytes      # Return the number of bytes consumed by the array "arr1".

28

# Working with arrays

In [14]:
my_array=np.array(np.random.randint(0,10,10))  # random.randint is another function in numpy which gives 10 random values starting from 0 to 10.
my_array                                       # Syntax - np.random.randint(start,stop,number_of_values)

array([4, 0, 3, 1, 3, 1, 7, 9, 2, 7])

In [15]:
np.min(my_array)  # Returns the minimum value from array.

0

In [16]:
np.max(my_array) # Returns maximum value from array.

9

In [17]:
np.argmin(my_array) # Returns index value of minimum element of array.

1

In [18]:
np.argmax(my_array) # Return index value of maximum element of array.

7

In [19]:
np.sort(my_array)   # Return elements in a sorted order.

array([0, 1, 1, 2, 3, 3, 4, 7, 7, 9])

In [20]:
np.argsort(my_array) # Returns the index values of array in the sorted order.


array([1, 3, 5, 8, 2, 4, 0, 6, 9, 7], dtype=int64)

#  More working with arrays...


In [21]:
num=np.array([1,4,5,10,11,2])
num

array([ 1,  4,  5, 10, 11,  2])

In [22]:
sum=0
for i in num:
    sum+=i
sum

33

In [23]:
np.sum(num)  # Returns the sum of all elements from the array 


33

In [24]:
np.sin(num)   # Returns the sine value of all elements from the array. 

array([ 0.84147098, -0.7568025 , -0.95892427, -0.54402111, -0.99999021,
        0.90929743])

In [25]:
np.log(num)    # Return the logarithmic value of each element from the array with base e.

array([0.        , 1.38629436, 1.60943791, 2.30258509, 2.39789527,
       0.69314718])

In [26]:
np.sqrt(num)   # Returns the square_root of each element from the array. 

array([1.        , 2.        , 2.23606798, 3.16227766, 3.31662479,
       1.41421356])