In [1]:
import numpy as np

# Multidimensional Arrays

In [2]:
ar1=np.array([
                [1,2,3],
                [4,5,6]
            
            ])


ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
ar1.ndim   # Returns dimension of array, '2'(2D) in this case.


2

In [4]:
ar1.dtype

dtype('int32')

In [5]:
ar1.shape

(2, 3)

In [6]:
ar1.size

6

In [7]:
np.where(ar1>3,1,0)  # np.where(condition,True_, False_)
                    # If the condition is true it return "True_" else returns "False_".

array([[0, 0, 0],
       [1, 1, 1]])

# Conversion


2D ARRAY INTO 1D ARRAY

In [8]:
my_ar=np.array([
                    [2,4,6],
                    [8,10,12]
    
               ])
my_ar

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
my_ar.ndim

2

In [10]:
my_ar.flatten()      #flatten() changes the 2-D Array into 1-D Array.
                     #It combines the rows of the 2-D Array.

array([ 2,  4,  6,  8, 10, 12])

In [11]:
my_ar.flatten().ndim

1

1D ARRAY INTO 2D ARRAY OR INTO ANY MULTIDIMENSIONAL ARRAY

In [12]:
new_ar=np.array([1,2,3,4,5,6,7,8,9])
new_ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
new_ar2=new_ar.reshape(3,3)     #Syntax- array_name.reshape(dim_1,dim_2)
new_ar2                         #reshape() function changes the dimension of the 1-D Array into dim_1 and dim_2.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
new_ar2=new_ar2.flatten()
new_ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
new_ar2.reshape(5,5)

ValueError: cannot reshape array of size 9 into shape (5,5)

# Matrix

In [16]:
numbers=np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                ])
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
mat = np.matrix(numbers)        #Numpy Array is converted into a Matrix using matrix() function.
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
mat_2 = np.matrix(" 1,2,3;4,5,6;7,8,9  ")      #Another Way of forming a Matrix directly with the values.
mat_2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
np.diagonal(mat)   # Will display the left diagonal

array([1, 5, 9])

In [20]:
np.fliplr(mat).diagonal()   # Will display the right diagonal

matrix([[3, 5, 7]])

In [21]:
np.min(mat)      #Will display the minimum value of the  element in the matrix

1

In [22]:
np.max(mat)    #Will display the maximum value of the element in the Matrix

9

OPERATIONS YOU CAN PERFORM ON 2 OR MORE DIFFERENT MATRICES

In [23]:
mat + mat_2        #Will add the two Matrices

matrix([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [24]:
mat - mat_2       #Will subtract the two Matrices

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [25]:
mat * mat_2       #Will give product of the two Matrices

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [26]:
mat / mat_2      #Will Divide the Two matrices

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Concatenation of 2 arrays

In [27]:
arr1=np.array([10,20,30,40])
arr1

array([10, 20, 30, 40])

In [28]:
arr2=np.array([90,80,70,60])
arr2

array([90, 80, 70, 60])

In [29]:
np.concatenate([arr1,arr2])           #Syntax- concatenate([array_1,array_2])
                                      #Will concatenate the two arrays into a single array

array([10, 20, 30, 40, 90, 80, 70, 60])

# Copying an array into another array

In [30]:
nums=np.array([1,2,3,4,5])
nums

array([1, 2, 3, 4, 5])

In [31]:
nums_copy = nums       

In [32]:
nums

array([1, 2, 3, 4, 5])

In [33]:
nums_copy

array([1, 2, 3, 4, 5])

In [34]:
nums_copy[2] = 100

In [35]:
nums_copy

array([  1,   2, 100,   4,   5])

In [36]:
nums      # Here comes the concept of deep copy and shallow copy.

array([  1,   2, 100,   4,   5])

In [37]:
nums_copy=nums.copy()    # .copy() is for deep copy

                         # .view() is for shallow copy. When you copy an array using assignment operator so by default it uses the concept of shallow copy.


In [38]:
nums_copy[2]=3

In [39]:
nums_copy   #Here the value of the nums_copy is changed now after applying copy() function in the above cell.

array([1, 2, 3, 4, 5])

In [40]:
nums      #Here the value of the index 2 is not changed when we apply copy() function depicting the concept of deep copy.

array([  1,   2, 100,   4,   5])